# -*- coding: utf-8 -*-
"""Wprowadzenie do research notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YqiXrNNR6x10WgKDBA6DcWU4w2goMiZb

# Import bibliotek
"""

import os
import pandas as pd

!pip install tensorflow

from platform import python_version
python_version()

"""# Przygotowanie danych do analizy"""

os.getcwd()

from google.colab import drive
drive.mount("/content/drive")

os.chdir("/content/drive/MyDrive/Colab Notebooks/datasets/")

base_data = pd.read_csv("DSP_4.csv")

base_data

df = pd.read_csv("DSP_4.csv", sep=";")
df

print(df)

df.columns

df.isnull().any()

print(df["wiek"].mean())
print(df["wzrost"].mean())

df_2 = df.fillna(df.mean())
df_2

df_2.isnull().any()

"""# Podstawowe statystyki opisowe"""

print(df_2["wiek"].mean())
print(round(df_2["wiek"].mean(), 2))
print(df_2["wiek"].median())
print(df_2["wiek"].max())
print(df_2["wiek"].min())
print(df_2["wiek"].var())

print(df_2.wiek.max() - df_2.wiek.min())

df_2.wiek.quantile([.25, .5, .75])

print(round(df_2["wiek"].std(), 2))

print(round(df_2.describe(), 2))

df_2["wiek"].groupby(df_2["objawy"]).describe()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from scipy.stats import pearsonr

df_2.corr()

sns.heatmap(df_2.corr())

plt.figure(figsize=(10,5))
heatmap = sns.heatmap(df_2.corr(), vmin=-1, vmax=1, annot=True)
heatmap.set_title("Analiza korelacji", fontdict={"fontsize": 14}, pad=12)

"""# Zadanie domowe"""

pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 5)
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.precision', 3)

display(df_2)